// Package service installs deckhand as a login service (launchd on macOS,
// systemd user unit on Linux) — generated from the running binary's own path,
// so there are no templates to edit.
package service

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
)

const label = "com.deckhand.daemon"

// Paths the generator needs; kept explicit for tests.
type Spec struct {
	BinaryPath string // absolute path to the deckhand binary
	HomeDir    string // user home
	LogPath    string // service stdout/stderr capture
}

// LaunchdPlist renders the launchd agent for Spec.
func LaunchdPlist(s Spec) string {
	return fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by 'deckhand service install' — regenerate rather than edit. -->
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>%s</string>
  <key>ProgramArguments</key>
  <array>
    <string>%s</string>
    <string>up</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <!-- launchd's default PATH misses Homebrew, which breaks gh auth and
         docker CLI-context tooling. A PATH is not a credential. -->
    <key>PATH</key>
    <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>
  </dict>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key>
    <false/>
  </dict>
  <key>StandardOutPath</key>
  <string>%s</string>
  <key>StandardErrorPath</key>
  <string>%s</string>
</dict>
</plist>
`, label, s.BinaryPath, s.LogPath, s.LogPath)
}

// SystemdUnit renders the systemd user unit for Spec.
func SystemdUnit(s Spec) string {
	return fmt.Sprintf(`# Generated by 'deckhand service install' — regenerate rather than edit.
[Unit]
Description=deckhand — self-hosted GitHub Actions runner slots
After=network-online.target

[Service]
ExecStart=%s up
Restart=always
RestartSec=30

[Install]
WantedBy=default.target
`, s.BinaryPath)
}

func currentSpec() (Spec, error) {
	bin, err := os.Executable()
	if err != nil {
		return Spec{}, err
	}
	if resolved, err := filepath.EvalSymlinks(bin); err == nil {
		bin = resolved
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return Spec{}, err
	}
	return Spec{
		BinaryPath: bin,
		HomeDir:    home,
		LogPath:    filepath.Join(home, ".deckhand", "service.log"),
	}, nil
}

func unitPath(s Spec) string {
	if runtime.GOOS == "darwin" {
		return filepath.Join(s.HomeDir, "Library", "LaunchAgents", label+".plist")
	}
	return filepath.Join(s.HomeDir, ".config", "systemd", "user", "deckhand.service")
}

// Install writes the service definition and starts it.
func Install() error {
	s, err := currentSpec()
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(s.HomeDir, ".deckhand"), 0o700); err != nil {
		return err
	}
	path := unitPath(s)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}

	switch runtime.GOOS {
	case "darwin":
		if err := os.WriteFile(path, []byte(LaunchdPlist(s)), 0o600); err != nil {
			return err
		}
		// Re-installs: bootout any previous registration first (ignore
		// failure — it usually just means "not loaded").
		_ = exec.Command("launchctl", "bootout", fmt.Sprintf("gui/%d/%s", os.Getuid(), label)).Run()
		if out, err := exec.Command("launchctl", "bootstrap", fmt.Sprintf("gui/%d", os.Getuid()), path).CombinedOutput(); err != nil {
			return fmt.Errorf("launchctl bootstrap: %v: %s", err, strings.TrimSpace(string(out)))
		}
		fmt.Printf("installed %s\nstarted via launchd (runs at login; logs: %s and ~/.deckhand/daemon.log)\n", path, s.LogPath)
	case "linux":
		if err := os.WriteFile(path, []byte(SystemdUnit(s)), 0o644); err != nil {
			return err
		}
		if out, err := exec.Command("systemctl", "--user", "daemon-reload").CombinedOutput(); err != nil {
			return fmt.Errorf("systemctl daemon-reload: %v: %s", err, strings.TrimSpace(string(out)))
		}
		if out, err := exec.Command("systemctl", "--user", "enable", "--now", "deckhand").CombinedOutput(); err != nil {
			return fmt.Errorf("systemctl enable --now: %v: %s", err, strings.TrimSpace(string(out)))
		}
		fmt.Printf("installed %s\nstarted via systemd --user\n", path)
		// Without lingering the unit dies at logout and won't start at boot.
		if err := exec.Command("loginctl", "enable-linger").Run(); err == nil {
			fmt.Println("enabled lingering (daemon survives logout and starts at boot)")
		} else {
			fmt.Println("note: run `loginctl enable-linger` so the daemon survives logout")
		}
	default:
		return fmt.Errorf("service install not supported on %s (run `deckhand up` under your own supervisor)", runtime.GOOS)
	}
	return nil
}

// Uninstall stops the service and removes its definition.
func Uninstall() error {
	s, err := currentSpec()
	if err != nil {
		return err
	}
	path := unitPath(s)
	switch runtime.GOOS {
	case "darwin":
		_ = exec.Command("launchctl", "bootout", fmt.Sprintf("gui/%d/%s", os.Getuid(), label)).Run()
	case "linux":
		_ = exec.Command("systemctl", "--user", "disable", "--now", "deckhand").Run()
	}
	if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	fmt.Println("service removed (the daemon, if running, was stopped)")
	return nil
}

// Status prints whether the service is registered and running.
func Status() error {
	s, err := currentSpec()
	if err != nil {
		return err
	}
	if _, err := os.Stat(unitPath(s)); err != nil {
		fmt.Println("service: not installed (deckhand service install)")
		return nil
	}
	switch runtime.GOOS {
	case "darwin":
		out, err := exec.Command("launchctl", "print", fmt.Sprintf("gui/%d/%s", os.Getuid(), label)).Output()
		if err != nil {
			fmt.Println("service: installed but NOT loaded (deckhand service install to re-register)")
			return nil
		}
		state := "unknown"
		for _, line := range strings.Split(string(out), "\n") {
			if strings.Contains(line, "state =") {
				state = strings.TrimSpace(strings.SplitN(line, "=", 2)[1])
				break
			}
		}
		fmt.Printf("service: installed, launchd state: %s\n", state)
	case "linux":
		out, _ := exec.Command("systemctl", "--user", "is-active", "deckhand").Output()
		fmt.Printf("service: installed, systemd state: %s\n", strings.TrimSpace(string(out)))
	}
	return nil
}
