// Package service installs deckhand as a login service (launchd on macOS,
// systemd user unit on Linux) — generated from the running binary's own path,
// so there are no templates to edit. Each instance (org/repo) installs its own
// unit so several can run side by side on one machine.
package service

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"
)

const defaultLabel = "com.deckhand.daemon"

// labelFor is the launchd label / launchd target suffix for an instance. The
// legacy default (empty name) keeps the original label so an already-installed
// service is untouched.
func labelFor(instance string) string {
	if instance == "" {
		return defaultLabel
	}
	return "com.deckhand." + instance
}

// systemdName is the systemd user unit name for an instance.
func systemdName(instance string) string {
	if instance == "" {
		return "deckhand"
	}
	return "deckhand-" + instance
}

// Paths the generator needs; kept explicit for tests.
type Spec struct {
	BinaryPath   string // absolute path to the deckhand binary
	HomeDir      string // OS user home (the unit file lives under here)
	Instance     string // instance name; "" is the legacy default
	InstanceHome string // the instance's state dir (DECKHAND_HOME for the daemon)
	LogPath      string // service stdout/stderr capture
}

// LaunchdPlist renders the launchd agent for Spec.
func LaunchdPlist(s Spec) string {
	// launchd's default PATH misses Homebrew, which breaks gh auth and docker
	// CLI-context tooling. A PATH is not a credential.
	env := "    <key>PATH</key>\n    <string>/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin</string>"
	if s.Instance != "" {
		// Non-default instances pin their home so the daemon targets the right
		// instance regardless of where launchd starts it.
		env += fmt.Sprintf("\n    <key>DECKHAND_HOME</key>\n    <string>%s</string>", s.InstanceHome)
	}
	return fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by 'deckhand service install' — regenerate rather than edit. -->
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>%s</string>
  <key>ProgramArguments</key>
  <array>
    <string>%s</string>
    <string>up</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
%s
  </dict>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key>
    <false/>
  </dict>
  <key>StandardOutPath</key>
  <string>%s</string>
  <key>StandardErrorPath</key>
  <string>%s</string>
</dict>
</plist>
`, labelFor(s.Instance), s.BinaryPath, env, s.LogPath, s.LogPath)
}

// SystemdUnit renders the systemd user unit for Spec.
func SystemdUnit(s Spec) string {
	envLine := ""
	if s.Instance != "" {
		envLine = "Environment=DECKHAND_HOME=" + s.InstanceHome + "\n"
	}
	return fmt.Sprintf(`# Generated by 'deckhand service install' — regenerate rather than edit.
[Unit]
Description=deckhand — self-hosted GitHub Actions runner slots
After=network-online.target

[Service]
%sExecStart=%s up
Restart=always
RestartSec=30

[Install]
WantedBy=default.target
`, envLine, s.BinaryPath)
}

func currentSpec(instance, instanceHome string) (Spec, error) {
	bin, err := os.Executable()
	if err != nil {
		return Spec{}, err
	}
	if resolved, err := filepath.EvalSymlinks(bin); err == nil {
		bin = resolved
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return Spec{}, err
	}
	if instanceHome == "" {
		instanceHome = filepath.Join(home, ".deckhand")
	}
	return Spec{
		BinaryPath:   bin,
		HomeDir:      home,
		Instance:     instance,
		InstanceHome: instanceHome,
		LogPath:      filepath.Join(instanceHome, "service.log"),
	}, nil
}

func unitPath(s Spec) string {
	if runtime.GOOS == "darwin" {
		return filepath.Join(s.HomeDir, "Library", "LaunchAgents", labelFor(s.Instance)+".plist")
	}
	return filepath.Join(s.HomeDir, ".config", "systemd", "user", systemdName(s.Instance)+".service")
}

// Install writes the service definition for one instance and starts it.
func Install(instance, instanceHome string) error {
	s, err := currentSpec(instance, instanceHome)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(s.InstanceHome, 0o700); err != nil {
		return err
	}
	path := unitPath(s)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}

	switch runtime.GOOS {
	case "darwin":
		domain := fmt.Sprintf("gui/%d", os.Getuid())
		target := domain + "/" + labelFor(s.Instance)
		loaded := func() bool {
			return exec.Command("launchctl", "print", target).Run() == nil
		}
		unchanged := false
		if prev, err := os.ReadFile(path); err == nil && string(prev) == LaunchdPlist(s) {
			unchanged = true
		}
		if unchanged && loaded() {
			// Re-running install must be a safe no-op-plus-restart, never an
			// error and never a torn-down service.
			_ = exec.Command("launchctl", "kickstart", "-k", target).Run()
			fmt.Println("already installed — restarted the service")
			return nil
		}
		if err := os.WriteFile(path, []byte(LaunchdPlist(s)), 0o600); err != nil {
			return err
		}
		// Replacing a loaded job: bootout, then WAIT for launchd to actually
		// unload it — an immediate re-bootstrap races and fails with
		// "Bootstrap failed: 5: Input/output error".
		if loaded() {
			_ = exec.Command("launchctl", "bootout", target).Run()
			for i := 0; i < 20 && loaded(); i++ {
				time.Sleep(250 * time.Millisecond)
			}
		}
		var out []byte
		var bootErr error
		for attempt := 0; attempt < 3; attempt++ {
			if out, bootErr = exec.Command("launchctl", "bootstrap", domain, path).CombinedOutput(); bootErr == nil {
				break
			}
			time.Sleep(time.Second)
		}
		if bootErr != nil {
			return fmt.Errorf("launchctl bootstrap: %v: %s", bootErr, strings.TrimSpace(string(out)))
		}
		fmt.Printf("installed %s\nstarted via launchd (runs at login; logs: %s and %s)\n", path, s.LogPath, filepath.Join(s.InstanceHome, "daemon.log"))
	case "linux":
		unit := systemdName(s.Instance)
		if err := os.WriteFile(path, []byte(SystemdUnit(s)), 0o644); err != nil {
			return err
		}
		if out, err := exec.Command("systemctl", "--user", "daemon-reload").CombinedOutput(); err != nil {
			return fmt.Errorf("systemctl daemon-reload: %v: %s", err, strings.TrimSpace(string(out)))
		}
		if out, err := exec.Command("systemctl", "--user", "enable", "--now", unit).CombinedOutput(); err != nil {
			return fmt.Errorf("systemctl enable --now: %v: %s", err, strings.TrimSpace(string(out)))
		}
		fmt.Printf("installed %s\nstarted via systemd --user\n", path)
		// Without lingering the unit dies at logout and won't start at boot.
		if err := exec.Command("loginctl", "enable-linger").Run(); err == nil {
			fmt.Println("enabled lingering (daemon survives logout and starts at boot)")
		} else {
			fmt.Println("note: run `loginctl enable-linger` so the daemon survives logout")
		}
	default:
		return fmt.Errorf("service install not supported on %s (run `deckhand up` under your own supervisor)", runtime.GOOS)
	}
	return nil
}

// Uninstall stops one instance's service and removes its definition.
func Uninstall(instance, instanceHome string) error {
	s, err := currentSpec(instance, instanceHome)
	if err != nil {
		return err
	}
	path := unitPath(s)
	switch runtime.GOOS {
	case "darwin":
		_ = exec.Command("launchctl", "bootout", fmt.Sprintf("gui/%d/%s", os.Getuid(), labelFor(s.Instance))).Run()
	case "linux":
		_ = exec.Command("systemctl", "--user", "disable", "--now", systemdName(s.Instance)).Run()
	}
	if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	fmt.Println("service removed (the daemon, if running, was stopped)")
	return nil
}

// Status prints whether one instance's service is registered and running.
func Status(instance, instanceHome string) error {
	s, err := currentSpec(instance, instanceHome)
	if err != nil {
		return err
	}
	if _, err := os.Stat(unitPath(s)); err != nil {
		fmt.Println("service: not installed (deckhand service install)")
		return nil
	}
	switch runtime.GOOS {
	case "darwin":
		out, err := exec.Command("launchctl", "print", fmt.Sprintf("gui/%d/%s", os.Getuid(), labelFor(s.Instance))).Output()
		if err != nil {
			fmt.Println("service: installed but NOT loaded (deckhand service install to re-register)")
			return nil
		}
		state := "unknown"
		for _, line := range strings.Split(string(out), "\n") {
			if strings.Contains(line, "state =") {
				state = strings.TrimSpace(strings.SplitN(line, "=", 2)[1])
				break
			}
		}
		fmt.Printf("service: installed, launchd state: %s\n", state)
	case "linux":
		out, _ := exec.Command("systemctl", "--user", "is-active", systemdName(s.Instance)).Output()
		fmt.Printf("service: installed, systemd state: %s\n", strings.TrimSpace(string(out)))
	}
	return nil
}
